[BE] Ver reuniones creadas
10PinesLabs/ruth pull request #266
Opened 2021-07-01 18:23 UTC by mpelozzi

[Ver reuniones creadas](https://trello.com/c/zhZIuCeO)

**Aceptación**
Se creó un endpoint para buscar las reuniones que están cerradas

**Checklist**:
- [X] Agregue tests (y los corrí localmente)
- [X] Vi que localmente funcionara
- [ ] Probe que en la review app funcionara

No pude revisar que esto funcionara desde la app porque sólo armé la parte del backend.

2021-07-01 18:44 UTC, NicoleBlasco requested changes
En backend/src/domain/reuniones/router.js cambiar ruteo.

2021-07-01 18:44 UTC, NicoleBlasco commented on backend/src/domain/reuniones/router.js
> +router.get('/reuniones', asyncMiddleware(controller.obtenerReuniones));
Acá esta el mismo get dos veces => router.get('/reuniones'). 
¿No habría que diferenciar el get de reuniones/abiertas del get de reuniones/cerradas? ¿Y obtenerReuniones no requiere un parámetro?

2021-07-01 18:54 UTC, mpelozzi commented on backend/src/domain/reuniones/router.js
> +router.get('/reuniones', asyncMiddleware(controller.obtenerReuniones));
No había visto la línea duplicada. La ruta para los dos es la misma, lo que va a cambiar va a ser el query param dependiendo de la reunión que quieras ver. Podés ver los ejemplos en los tests.

2021-07-01 19:09 UTC, NicoleBlasco approved these changes

2021-07-02 13:25 UTC, SantiagoParedes97 requested changes
Deje un par de comments, creo que el mas importante es la parte del FE, pero el resto tambien esta bueno hacerlos

2021-07-02 13:25 UTC, SantiagoParedes97 commented on backend/src/domain/reuniones/reuniones.test.js
> +    const reunionesCerradas = await request(app).get('/api/reuniones?estaAbierta=false');
Podriamos agregar un expect para el status que devuelve? (Deberia devolver 200)

2021-07-02 13:25 UTC, SantiagoParedes97 commented on backend/src/domain/reuniones/router.js
> +router.get('/reuniones', asyncMiddleware(controller.obtenerReuniones));
Con este cambio, el FE sigue funcionando? 👀

2021-07-02 13:25 UTC, SantiagoParedes97 commented on backend/src/domain/reuniones/reuniones.test.js
> +    expect(reunionesCerradas.body.reuniones[0].id).toEqual(reunionAbierta.id);
Estaria bueno testear que toda la respuesta es correcta, si devuelvo solo esto:
`{
reuniones: [{
 id: 1,
 temas:[{
  id: 2
 }]
}]}`

¿Eso esta bien? ¿El test pasa?

(Verificar eso se puede hacer por partes o poner un solo expect con un objecto que represente toda la response en frente)

2021-07-02 13:54 UTC, mpelozzi commented on backend/src/domain/reuniones/reuniones.test.js
> +    expect(reunionesCerradas.body.reuniones[0].id).toEqual(reunionAbierta.id);
Quise testear que las reuniones sean iguales pero no puedo porque los tiempos de modificación y creación se diferencian por milisegundos y me falla el test. Igual puedo probarlo por partes, pero no estoy segura de cómo testear el createdAt y el updatedAt. Otra cosa que me gustaría testear es que si le mando cualquier cosa a la ruta al front le debería llegar un 404, ahora defaultea a devolver las reuniones cerradas, no estoy muy segura de cómo devolver un status code :eyes:  es lo que estoy investigando.

2021-07-02 13:56 UTC, mpelozzi commented on backend/src/domain/reuniones/router.js
> +router.get('/reuniones', asyncMiddleware(controller.obtenerReuniones));
Este cambio lo hizo Nicky desde el frontend, no estoy segura de si me corresponde a mi o no porque el ticket era solo sobre el backend. Debería cambiarlo yo y que Nicky se adapte?

2021-07-02 14:00 UTC, SantiagoParedes97 commented on backend/src/domain/reuniones/router.js
> +router.get('/reuniones', asyncMiddleware(controller.obtenerReuniones));
Osea, sip, es un ticket mayormente de BE, pero al refactorizar las rutas tenes que cambiar algo en el FE para que quede vivo 😅, porque no tiene sentido mergear el PR sin eso

2021-07-02 14:05 UTC, mpelozzi commented on backend/src/domain/reuniones/reuniones.test.js
> +    const reunionesCerradas = await request(app).get('/api/reuniones?estaAbierta=false');
done

2021-07-02 14:08 UTC, SantiagoParedes97 commented on backend/src/domain/reuniones/reuniones.test.js
> +    expect(reunionesCerradas.body.reuniones[0].id).toEqual(reunionAbierta.id);
Sobre lo primero, lo que deberias hacer es que la fecha sea estable durante todo tu test, mockeando la fecha
ejemplo (puede haber otras formas de hacerlo) https://codewithhugo.com/mocking-the-current-date-in-jest-tests/
Sobre lo segundo, podria ser, tambien podria ser valido que defaultee a las cerradas, no es algo que me molesta actualmente, pero si, se podria hacer fijandote que ese parametro exista y sea uno de los 2 valores validos, y si no es ninguno de esos 2, devolver 400

2021-07-02 15:13 UTC, mpelozzi commented on backend/src/domain/reuniones/router.js
> +router.get('/reuniones', asyncMiddleware(controller.obtenerReuniones));
done

2021-07-02 15:14 UTC, angelyan commented on backend/src/domain/reuniones/router.js
> +router.get('/reuniones', asyncMiddleware(controller.obtenerReuniones));
Recuerden que la idea es que `master` esté siempre funcionando. Si se mergeara esto sin el cambio en el front quedaría rota la app en esa rama.

2021-07-02 15:19 UTC, angelyan commented on backend/src/database/models/index.js
>  db.Sequelize = Sequelize;
Esto de acá parecería que no se está usando en ningún lado. Quizás se puede sacar. @SantiagoParedes97 podés confirmar que eso no va a romper nada? No estoy seguro de si se usa para algo en particular

2021-07-02 15:36 UTC, angelyan commented on backend/src/domain/reuniones/repo.js
> +  findAllWhereOpened(isOpened) {
Falta algún caso en los tests que agregaron?

Qué pasa si dejo esta implementación como `return models.Reunion.findAll()` y corro los tests para reuniones abiertas y luego para reuniones cerradas? Y qué pasa si corro todos los tests (tanto para reuniones abiertas como cerradas) juntos?

2021-07-02 15:38 UTC, angelyan commented on backend/src/domain/reuniones/repo.js
> +  findAllWhereOpened(isOpened) {
Avisen si no se entendió lo de correr los tests, capaz no me expliqué muy bien :sweat_smile:

2021-07-02 16:00 UTC, ludat requested changes

2021-07-02 16:01 UTC, angelyan commented on backend/src/domain/reuniones/reuniones.test.js
> +  });
spoilers de mi comentario :eyes:

2021-07-02 17:57 UTC, mpelozzi commented on backend/src/domain/reuniones/repo.js
> +  findAllWhereOpened(isOpened) {
ya hice los tests :)

2021-07-02 19:03 UTC, mpelozzi commented on backend/src/domain/reuniones/reuniones.test.js
> +  });
done

2021-07-02 19:03 UTC, mpelozzi commented on backend/src/domain/reuniones/reuniones.test.js
> +    expect(reunionesCerradas.body.reuniones.length).toEqual(0);
done

2021-07-02 19:06 UTC, mpelozzi commented on frontend/src/api/backend.js
>  export default Backend;
si hay cambios de linter pero estaba cambiando como el front usa la api también, y cuando formatee se formateo todo el archivo

2021-07-02 19:07 UTC, mpelozzi commented on backend/src/domain/reuniones/reuniones.test.js
> +    expect(reunionesCerradas.body.reuniones[0].temas[0].titulo).toEqual(temaGenerico.titulo);
ya hice un refactor sobre esto

2021-07-02 19:10 UTC, SantiagoParedes97 commented on backend/src/database/models/index.js
>  db.Sequelize = Sequelize;
@angelyan Osea, no estoy seguro para que se usa, pero puede que se use para algo de migraciones o algo similar maybe? Podria chusmearlo dsp pero dejaria afuera del PR,

2021-07-02 19:18 UTC, SantiagoParedes97 approved these changes
Lo apruebo, dejo un comentario opcional

2021-07-02 19:18 UTC, SantiagoParedes97 commented on backend/src/domain/reuniones/reuniones.test.js
> +      const response = await request(app).get('/api/reuniones?estaAbierta=true');
Esto se puede sacar al beforeEach, y estas const ponerlas en un let (por cada const) en el describe

2021-07-02 19:30 UTC, angelyan commented on backend/src/domain/reuniones/reuniones.test.js
> +  describe('para reuniones abiertas y cerradas', () => {
Me gusta cómo están agrupados estos tests! Tiene mucho sentido porque se trata de la misma "situación" (tener tanto reuniones abiertas como cerradas), sólo que se verifican acciones distintas. Pero como es la misma situación, se termina repitiendo mucho código de setup en los tests.

Algo que hace el `describe()`, además de agrupar tests, es definir un [scope para los setups y teardowns](https://jestjs.io/docs/setup-teardown#scoping). Es decir, se puede poner un `beforeEach()` acá y eso va a aplicar solamente a los tests de este `describe()`. Con eso podemos evitar repetir código en el setup y también quedan más claros y concisos los tests.

2021-07-05 11:25 UTC, mpelozzi commented on backend/src/domain/reuniones/reuniones.test.js
> +  describe('para reuniones abiertas y cerradas', () => {
listo :)

2021-07-05 11:26 UTC, mpelozzi commented on backend/src/domain/reuniones/reuniones.test.js
> +      const response = await request(app).get('/api/reuniones?estaAbierta=true');
listo :)

2021-07-05 12:38 UTC, angelyan approved these changes

2021-07-05 12:44 UTC, merged