Ver reuniones cerradas fe
10PinesLabs/ruth pull request #269
Opened 2021-07-05 14:20 UTC by NicoleBlasco

[[FE] - Ver reuniones cerradas](https://trello.com/c/quctgIrc)

**Aceptación**
Agrega la tab de reuniones cerradas (conseguidas desde el backend) con sus respectivas columnas:
- Nombre
- Autor
- Fecha
- Call to actions sin comportamiento

![Screenshot from 2021-07-05 11-15-46](https://user-images.githubusercontent.com/49131789/124485408-e60c8800-dd82-11eb-8e2c-ce6a0f41b5fb.png)
![Screenshot from 2021-07-05 11-18-47](https://user-images.githubusercontent.com/49131789/124485410-e6a51e80-dd82-11eb-9617-33c0205ffbf5.png)

**Checklist**:
- [ ] Agregue tests (y los corrí localmente)
- [X] Vi que localmente funcionara
- [ ] Probe que en la review app funcionara

2021-07-05 19:43 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +                            <StyledTableCell>Autor</StyledTableCell>
La unica diferencia entre ver las reuniones abiertas y las cerradas son los botones que se muestran no? Tdo olo demas seria lo mismo, tal vez se puede crear un componente que sea esa tabla y vos le pasas los Botones que queres mostrar

2021-07-05 19:43 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +        <StyledTableCell >{reunion.temas.length > 1 ? "Roots" : reunion.temas[0].autor}</StyledTableCell>
Podriamos reutilizar esto con lo de reuniones abiertas?

2021-07-05 19:43 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +    }*/
No se si es muy util dejarlo comentado, tal vez resulta mas engorroso de leer el componente con los comentarios que lo que aportan esos comentarios 😅

2021-07-05 19:43 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/Tab.js
> +                TabIndicatorProps={{style: {backgroundColor: '#448475'}}}
Yo intentaria hacer esto con styled-components, pero no es algo que me vuelve loco, tal vez es muy complejo de hacer con styled, pero le daria una chance

2021-07-05 19:43 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/Tab.js
> +            <SwipeableViews
No estaria entendiendo por que agregamos esta dependencia (Puede que me este perdiendo una interaccion D: ). Estaria viendo el mismo comportamient que si son tabs de material UI comunes 😅

2021-07-06 19:17 UTC, mpelozzi commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +        <StyledTableCell >{reunion.temas.length > 1 ? "Roots" : reunion.temas[0].autor}</StyledTableCell>
Ari había pedido que las reuniones cerradas se vean de la más reciente a la más vieja

2021-07-07 13:58 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/Tab.js
> +            <SwipeableViews
Agregue SwipeableViews porque, al cambiar de Tab, si no está la tabla de las reuniones aparece muy abruptamente. En cambio si está la tabla aparece desplazandose, lo cual es más ameno a la vista.

2021-07-07 17:11 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/Tab.js
> +                TabIndicatorProps={{style: {backgroundColor: '#448475'}}}
Lo intenté hacer antes y me volví loca :c

2021-07-07 17:13 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/Tab.js
> +            <SwipeableViews
Si aún así prefieren que hagan el cambio (que lo saque) lo hago

2021-07-08 15:08 UTC, SantiagoParedes97 reviewed
Deje un par de comments, tal vez estria bueno agregar un test de FE para la parte de ordenamiento

2021-07-08 15:08 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/Tab.js
> +    const theme = useTheme();
Probablemente estaria bueno otro nombre tipo: ReunionesTabs? MeetingsTabs?

2021-07-08 15:08 UTC, SantiagoParedes97 commented on frontend/src/styles/theme.js
> +  secondary: '#929b9e78',
Charlaron con Ari/Diseñador estos cambios? Porque estas cambiando el color para todos los que usen ese sencodary 👀

2021-07-08 15:08 UTC, SantiagoParedes97 commented on frontend/src/components/Button.styled.js
> +`;
No podemos reusar algo de Button? 👀 (Componente predefinido con algunas cosas similares)

2021-07-08 16:12 UTC, ludat requested changes
en general me parece que hay muchos problemas con el linter en este PR :eyes: y un par de comentarios aleatorios

2021-07-08 16:12 UTC, ludat commented on frontend/src/empezar-reunion/Tab.js
> +                        <ReunionCerradas/>
que onda con el `ReunionesActivasWrapper`? porque esta wrappeando a un `ReunionCerradas`, tiene sentido ese nombre si no va a wrappear solamente a las reuniones activas?

2021-07-08 16:12 UTC, ludat commented on frontend/src/empezar-reunion/Tab.js
> +import React from 'react';
Este archivo esta identado con 4 espacios, creo que la norma son 2 espacios en ruth

2021-07-08 16:12 UTC, ludat commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +            </Tooltip>
tiro que quiza podriamos usar esto https://material-ui.com/components/button-group/#split-button en vez de meter iconos?

2021-07-08 19:13 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/Reunion.js
> +    }
Tiene sentido. Ahora lo cambio.

2021-07-08 19:22 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/ReunionesActivas.js
>  const FilaReunion = ({reunion,history}) => {
¿Si se lo llama Reuniones en vez de Reunión en singular te parece que es más entendible?

2021-07-08 19:25 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/ReunionesActivas.js
>      return <>
Quedó en Reuniones eso ahora (el componente que abstrae toda la lógica repetida que tenía ReunionesCerradas y ReunionesActivas).

2021-07-08 19:26 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/Tab.js
> +    const theme = useTheme();
Si, tenés razon. Ahora lo cambio

2021-07-08 19:36 UTC, NicoleBlasco commented on frontend/src/styles/theme.js
> +  secondary: '#929b9e78',
Si, el mismo me dijo que lo cambie. De todas formas le consulto nuevamente porque quizas no sabía que también modifica un botón de guardar.

2021-07-08 19:40 UTC, NicoleBlasco commented on frontend/src/components/Button.styled.js
> +`;
Si, ahí lo cambio.

2021-07-08 20:05 UTC, NicoleBlasco commented on frontend/src/styles/theme.js
> +  secondary: '#929b9e78',
Confirmado. Le pregunté nuevamente y está de acuerdo con que el color secundario sea gris. De todas formas me dijo que al único botón que usaba ese color secundario para hacer el hover que le ponga otro nombre al color. Así que agrego eso.

2021-07-08 20:08 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/Reunion.js
> +import React, {useEffect, useState} from "react";
Tenia el linter desabilitado jiji ahora cambio todo

2021-07-08 20:29 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/Tab.js
> +            </SwipeableViews>
Santi me preguntó lo mismo más arriba, basicamente si no está cuando se cambia de Tab la tabla aparece de la nada. Si está SwipeableViews la tabla aparece deslizandose lo cual es más agradable a la vista.

2021-07-08 20:32 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +            </Tooltip>
Reusé los íconos que ya estaban porque era lo que Ari quería.

2021-07-08 20:45 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/Reunion.js
> +        <StyledTableCell >{reunion.temas.length > 1 ? "Roots" : reunion.temas[0].autor}</StyledTableCell>
Si pongo reunion.reunionDeRoots que es el booleano del que hablas no aparece lo mismo en la columna autor de la tabla que si lo dejo como está ahora.

2021-07-08 20:46 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/Tab.js
> +    const [value, setValue] = React.useState(0);
¿reunion te parece mejor? :D

2021-07-08 20:48 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/Tab.js
> +                        <ReunionCerradas/>
Tenes razón, tendría que ser ReunionesWrapper.

2021-07-12 21:50 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/Reunion.js
> +        <StyledTableCell >{reunion.temas.length > 1 ? "Roots" : reunion.temas[0].autor}</StyledTableCell>
Osea, si quieren lo vemos,p ero deberian ser similares  (Si no hay algo peor que esta pasando :P)

2021-07-12 22:42 UTC, ludat requested changes

2021-07-12 22:42 UTC, ludat commented on frontend/src/empezar-reunion/Reuniones.js
> +  </>;
esto suena que esta mal indentado :eyes: (4 espacios en vez de dos y los props van uno por linea cuando son tantos

2021-07-12 22:42 UTC, ludat commented on frontend/package.json
> +    "prop-types": "^15.7.2",
me suena que esto no es una devDependecy, no?

2021-07-13 12:16 UTC, NicoleBlasco commented on frontend/src/components/Button.styled.js
> -  font-family: ${font.p};
Porque estaba duplicado, más arriba esta

2021-07-13 12:35 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/Reuniones.js
> +      .then(({ reuniones }) => setReuniones(reuniones));
Puedo sacarla, pero me chilla el nombre reuniones por el ESLint. Y no me deja poner data.reuniones.

2021-07-13 12:39 UTC, NicoleBlasco commented on frontend/package.json
> +    "prop-types": "^15.7.2",
Se me chispoteo

2021-07-13 13:58 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/Reuniones.js
> +      .then(({ reuniones }) => setReuniones(reuniones));
Osea, te chilla porque tiene sentido, fijate que arriba estas declarando reuniones como parte del state. Diria que le busquemos otro nombre (rawReuniones?) o usemos data como dice Ludat

2021-07-13 15:10 UTC, ludat approved these changes

2021-07-13 15:10 UTC, merged