Conectar boton reenviar mail de minuta
10PinesLabs/ruth pull request #271
Opened 2021-07-12 15:40 UTC by NicoleBlasco

[Conectar botones de reuniones cerradas - reenviar mail de minuta](https://trello.com/c/LbCSHpK8)

**Aceptación**
Reenvia el mail de minuta al clickear el botón en una reunión específica. 

https://user-images.githubusercontent.com/49131789/125316180-4153f280-e30e-11eb-904c-2ec8aee0aa5e.mp4

**Checklist**:
- [ ] Agregue tests (y los corrí localmente)
- [X] Vi que localmente funcionara
- [ ] Probe que en la review app funcionara

2021-07-13 17:17 UTC, SantiagoParedes97 requested changes
Dejo un par de comments, ademas de eso:
¿Esta bien que pueda enviar un mail con un mail vacio?

2021-07-13 17:17 UTC, SantiagoParedes97 commented on backend/env.example
> -#Si está en false se le envía un mensaje directo al dueño del action item (buscandolo por su email) a slack.
creo que esto no deberia borrarse 👀

2021-07-13 17:17 UTC, SantiagoParedes97 commented on backend/src/domain/reuniones/controller.js
> +      await enviarResumenPorMail(null, reunionAActualizar, req.body.temas);
No tiene sentido aca pasarle el process.env.MAIL_DESTINATION en vez de null?

2021-07-13 17:17 UTC, SantiagoParedes97 commented on backend/src/utils/asyncMiddleware.js
> +      throw error;
Estamos seguros que queremos hacer esto? Recuerdo que @mpelozzi lo habia agregado hace relativamente poco, por que necesitamos cambiar esto?

2021-07-13 17:17 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/EmpezarReunion.styled.js
> +  border: 0;
Hablaron del diseño con Ari? Siento que el input podria ser bastante mas ancho, ocupando mas espacio

2021-07-13 17:17 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +    </>
Optional: este fragment se puede sacar :)

2021-07-13 17:17 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +    const state = useSelector(state => state);
No tenes la reunion por parametro, para que necesitas todo el state? 👀

2021-07-13 17:17 UTC, SantiagoParedes97 commented on frontend/src/styles/theme.js
> +import styled from "styled-components";
Por que necesitamos este import?

2021-07-13 17:17 UTC, SantiagoParedes97 commented on frontend/src/tipos-vista-principal/Modal.jsx
> +export const ModalDeConfirmacion = ({ title, open, onClose, onConfirm, cancelText="Cancelar", confirmText="Confirmar", Body, mail, setMail}) => (
Posiblemente body seria el componente que le pasas? Podria ser children y pasarlo como children

2021-07-13 17:17 UTC, SantiagoParedes97 commented on backend/src/domain/mail/controller.js
> +});
Algun test de esto? Como por ejemplo que llame al que envia los mails con lo que deberia pasarle

2021-07-13 17:17 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +        setMail(undefined);
No deberia cerrarse despues de que se envia?

2021-07-14 13:15 UTC, NicoleBlasco commented on backend/env.example
> -#Si está en false se le envía un mensaje directo al dueño del action item (buscandolo por su email) a slack.
No se por qué borre eso ni cuando lo hice. Me fije y en ninguno de los commits lo borré

2021-07-14 13:22 UTC, NicoleBlasco commented on backend/src/utils/asyncMiddleware.js
> +      throw error;
Lo hablé con Mori y Ludat y concordamos que era lo mejor.

2021-07-14 13:25 UTC, SantiagoParedes97 commented on backend/src/utils/asyncMiddleware.js
> +      throw error;
@NicoleBlasco el BE responde algo cuando no es un request error? (Le devuelve la response al FE con alguna info?) O queda en pendiente la request?

2021-07-14 13:27 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/EmpezarReunion.styled.js
> +  border: 0;
Sisi, está todo hablado la parte de los botones. No se si está bien que lo cambie en esta branch cuando está corregido en master.

2021-07-14 13:29 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +    </>
Con este fragment te referis a..? Los "piquitos" y poner directamente return <TextContainer...> ... </TextContainer...>?

2021-07-14 13:33 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +    const state = useSelector(state => state);
Eso ya no está ahora :/

2021-07-14 13:34 UTC, NicoleBlasco commented on frontend/src/styles/theme.js
> +import styled from "styled-components";
No se necesita, borrado.

2021-07-14 13:39 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +    </>
Sip, cuando pones <> estas hablando de https://es.reactjs.org/docs/fragments.html, y en este caso no son necesarios :)

2021-07-14 13:45 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +        setMail(undefined);
Si, increiblemente a pesar de que en el modal estaba primero onClose y luego onConfirm ya lo hacía. De todas formas lo cambio y verifico que no haya modificado a os demás componentes que utilizan el modal.

2021-07-14 14:30 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +    </>
Ahh bueno, quedó de ésta forma, ¿Te parece bien?
![Screenshot from 2021-07-14 11-29-12](https://user-images.githubusercontent.com/49131789/125639757-69827887-a4c3-44d7-bd13-11f08f1e30cd.png)

2021-07-14 20:25 UTC, NicoleBlasco commented on backend/src/utils/asyncMiddleware.js
> +      throw error;
Queda pendiente, es algo que tengo que cambiar todavía asi como que verifique que sea un mail válido desde el front. Igual ahora deje lo de Mori (hice el rebase y deje el res.status(500).send('Request fallo')).

2021-07-16 16:04 UTC, SantiagoParedes97 reviewed
Dejo un par de comments

2021-07-16 16:04 UTC, SantiagoParedes97 commented on backend/src/domain/mail/router.js
> +export default router;
Tiene sentido crear un router solo por esto? No seria mejor que este en la parte de reuniones?

2021-07-16 16:04 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +    eventos.forEach((evento) => store.dispatch({ ...evento.evento, comesFromWS: true })); // TODO cambiar comesFromWS
Cambiaria el comesFromWS a algo que represente lo que significa ese booleano (Que no debe ser publicado ese evento, ya que es un evento creado)

2021-07-16 16:14 UTC, NicoleBlasco commented on backend/src/domain/mail/router.js
> +export default router;
Creí que para reenviar un mail estaba bueno que esté en la parte de mails y no de reuniones. Entiendo que es solo un endpoint pero en eventos sucede lo mismo y sin embargo el router está.

2021-07-16 16:15 UTC, NicoleBlasco commented on backend/src/domain/mail/router.js
> +export default router;
Cambiarlo de lugar no es un problema, pero ¿Está bien hacerlo?

2021-07-20 16:04 UTC, angelyan commented on backend/src/domain/mail/mail.test.js
> +      expect(response.statusCode).toEqual(200);
Habría que verificar que se estén mandando los mails también. Para eso se podría ver de mockear nodemailer.

2021-07-20 16:21 UTC, angelyan commented on backend/src/domain/reuniones/reuniones.test.js
> +      expect(response.body.eventos[0].reunionId).toEqual(evento.body.reunionId);
Esto se usa en varios lugares, se podría extraer en una función

2021-07-21 19:09 UTC, FdelMazo commented
Hay mas rebases en este PR que en todo github junto creo

2021-07-21 19:21 UTC, SantiagoParedes97 commented on backend/src/domain/reuniones/reuniones.test.js
> +
Diria de pasarle solo el evento no? (En vez de la response +posicionEnLaResponse) [Digo de pasarle los dos evnetos, el que te devuelve la api y el que deberia ser, y comparar esos eventos]

2021-07-21 19:21 UTC, SantiagoParedes97 commented on backend/src/domain/reuniones/reuniones.test.js
> +        mail: 'leda.graham74@ethereal.email',
Podemos sacar a una constante esto? (Se usa en varios lados, y se entiende mejor si se saca a una constante)

2021-07-21 19:21 UTC, SantiagoParedes97 commented on backend/src/domain/reuniones/reuniones.test.js
> +      const response = await request(app).get(`/api/reuniones/${reunionAbierta.id}/eventos`);
En vez de hacer 2 request, podrias crearte los eventos y guardatelos en el EventoRepo y despues recien hacer la request para ver si la reunion te devuelve los eventos correctos

2021-07-21 19:21 UTC, SantiagoParedes97 commented on backend/src/domain/reuniones/reuniones.test.js
> +    });
Faltaria un test que verifique que traiga solo los eventos de esa reunion no?

2021-07-22 13:12 UTC, angelyan commented on backend/src/domain/reuniones/reuniones.test.js
> +      });
Quedó muy bien lo del mock! :clap:

Quizás no tiene tanto sentido verificar la configuración del `nodemailer.createTransport` porque es una configuración para los tests nomás. La app real usa otros valores. Me parece suficiente con el expect de abajo.

2021-07-22 13:39 UTC, NicoleBlasco commented on backend/src/domain/reuniones/reuniones.test.js
> +      });
Gracias, lo hice con Santi. Eso está también para verificar que lo que se le manda sea lo que le llega, además de verificar que se estén mandando los mails.

2021-07-22 17:05 UTC, SantiagoParedes97 approved these changes
🐰

2021-07-22 17:16 UTC, angelyan commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +      backend.reenviarMailMinuta(email, state.reunion.temas, state.reunion.id).then(toast.success(`Mail de minuta enviado a ${email}`));
Tengo una duda acá :thinking: 

Entiendo que todo esto del store y aplicar los eventos es para actualizar la reunión y los temas y pasarle la info actualizada al back. Si eso correcto, mi pregunta es: por qué hacemos eso acá en vez de dejar que el back se encargue?

En mi cabeza esto sería simplemente
```js
backend.reenviarMailMinuta(email, state.reunion.id)
    .then(toast.success(`Mail de minuta enviado a ${email}`));
```
sin hacer todo lo del store.

Hay algo que no estoy viendo acá?

cc @SantiagoParedes97

2021-07-22 17:22 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +      backend.reenviarMailMinuta(email, state.reunion.temas, state.reunion.id).then(toast.success(`Mail de minuta enviado a ${email}`));
Osea, si me preguntas a modo meta, sip, en mi cabeza tambien tiene sentido que lo haga en el back. La respuesta es: Todo el manejo de que significan los eventos solo lo entiende el FE, el BE no entiende nada de los eventos mas que guardarlos, e implica un refactor mucho mas grande que el ticket. Eso esta asi porque el FE funciona asi por ahora, podria moverse al BE? Sip, pero implicaria basicamente cambiar el core de la aplicacion bastante, y ver que eso siga funcionando bien. El BE no entiende del estado de la reunion ni como construirlo, y tenerlo en los dos lugares seria como bastante horrible.

Ese seria el contexto, poder se puede cambiar, excede por muchisimo al ticket de este PR, podria ser un ticket de deuda tecnica maybe, pero deberiamos primero juntarnos y ver que estamos seguros de que queremos hacer ese refactor gigante 🙃

2021-07-22 17:32 UTC, angelyan commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +      backend.reenviarMailMinuta(email, state.reunion.temas, state.reunion.id).then(toast.success(`Mail de minuta enviado a ${email}`));
O sea que el backend no tiene guardada la última versión de la reunión y los temas? :thinking:

2021-07-22 17:37 UTC, NicoleBlasco commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +      backend.reenviarMailMinuta(email, state.reunion.temas, state.reunion.id).then(toast.success(`Mail de minuta enviado a ${email}`));
Si, estaría bueno reducir los eventos desde el backend pero ahora se hace únicamente desde el front y cambiarlo tomaría mucho tiempo (además de que agrandaría bastante el ticket). Seguramente habrá un ticket para cambiarlo.

2021-07-22 17:40 UTC, merged

2021-07-22 18:13 UTC, SantiagoParedes97 commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +      backend.reenviarMailMinuta(email, state.reunion.temas, state.reunion.id).then(toast.success(`Mail de minuta enviado a ${email}`));
@angelyan Esos temas que tiene son literalmente el tema (Know as descripcion, duracion, etc), como los que vienen de votacion de ruth. Todo lo que paso dentro del tema (interacciones), no esta incluido en el tema en si, sino que se reduce desde la parte de los eventos para esa reunion y para ese tema. 
El BE tiene guardado las reuniones y sus temas, pero por como esta organizado, el tema no sabe quien opino ni su minuta, ni ninguna interaccion de la reunion

2021-07-22 18:31 UTC, angelyan commented on frontend/src/empezar-reunion/ReunionesCerradas.js
> +      backend.reenviarMailMinuta(email, state.reunion.temas, state.reunion.id).then(toast.success(`Mail de minuta enviado a ${email}`));
Ah ok. :F: