Conectar botones reunion cerrada
10PinesLabs/ruth pull request #272
Opened 2021-07-15 12:42 UTC by mpelozzi

[**Link al Trello**](https://trello.com/c/etIcPSIb)

**Aceptación**
Conecta el botón para ver las reuniones cerradas. Bloquea los botones de empezar/rebrir tema, editar minutas y action items, y cerrar reunion si la reunión ya está cerrada. Agrega un tooltip para especificar que los botones están deshabilitados porque la reunión está cerrada. Agrega validaciones para que no se puedan publicar eventos a una reunión que ya está cerrada.

**Checklist**:
- [X] Agregue tests (y los corrí localmente)
- [X] Vi que localmente funcionara
- [ ] Probe que en la review app funcionara

2021-07-15 15:08 UTC, ludat requested changes

2021-07-15 15:08 UTC, ludat commented on frontend/src/store/index.js
> +  if (!state.reunion || state.reunion.abierta || !state.reunion.abierta) {
`booleano || !booleano` no suena como algo que queremos

2021-07-15 15:08 UTC, ludat commented on frontend/src/store/reunion.js
> +        draft.reunion.abierta = true;
Ojo que aca estas editando el objeto original, lo cual es bastante mala idea, mejor hacerlo con el spread operator

2021-07-15 15:08 UTC, ludat commented on frontend/src/styles/CustomTooltip.js
> +                    open={disable ? undefined : false}>
algo medio personal pero no me encanta alinear las props al nombre del componente (si el componente cambia de nombre el diff es gigante al dope) pero no es blocker

2021-07-15 15:08 UTC, ludat commented on frontend/src/tipos-vista-principal/Resumen.js
> +    'proponerPinos': DescripcionPropuestaPinos,
que onda esto cambios?

2021-07-15 15:08 UTC, ludat commented on frontend/src/tipos-vista-principal/Resumen.js
> +const Resumen = ({
este formateo de cosas lo hizo intellij o el linter? esta usando 4 espacios en vez de 2, y significa cambia la mayoria de las lineas de este archivo, suena como que es medio mucho para este PR

2021-07-15 15:08 UTC, ludat commented on frontend/src/tipos-vista-principal/Resumen.js
> +        <VistaDelMedioContainer style={props}>
con el cambio de formateo me cuenta mucho ver que cosas con cambios de verdad y cuales son cambios de identacion

2021-07-15 15:31 UTC, mpelozzi commented on backend/src/utils/asyncMiddleware.js
> +      res.status(500).send('Request fallo');
Creo que tiene sentido tirar un 500 si salta un error no contemplado, porque el resto de los errores que tira la aplicación los conozco y son instancia de RequestError. Cualquier cosa que no lo sea instancia es un error que de alguna forma se le debería comunicar al frontend. Si por ejemplo queda en pendiente una promesa, el front no se va a enterar, y va a saltar un timeout (que es lo que le pasó a nicky ayer y por eso volvimos a esta solución).

2021-07-15 15:36 UTC, mpelozzi commented on frontend/src/api/requester.js
> +    }
Por los espacios extra o por las indentaciones?

2021-07-15 15:41 UTC, mpelozzi commented on frontend/src/reunion/TemasHandler.js
> +            .then(() => {
no había visto esto, pero al final ya no se debería _tostear_ con reunión cerrada porque eso pasaba cuando no estaba bloqueado el botón de cerrar en las reuniones cerradas, ahora lo cambio

2021-07-15 15:42 UTC, mpelozzi commented on frontend/src/reunion/TemasHandler.js
> +                }
En ninguno ya, es lo que respondí arriba

2021-07-15 15:44 UTC, ludat commented on backend/src/utils/asyncMiddleware.js
> +      res.status(500).send('Request fallo');
ah okas, entonces aca hace falta un `console.error` porque si no el backend se estaria tragando el error como un campeon

2021-07-15 15:45 UTC, mpelozzi commented on frontend/src/reunion/VistaTemas.js
> +    if(!reunionAbierta){
no se queja desde mi ide :thinking: es raro porque hay ifs escritos de las dos formas y con ningua se queja

2021-07-15 15:47 UTC, mpelozzi commented on frontend/src/store/index.js
> +  if (!state.reunion || state.reunion.abierta || !state.reunion.abierta) {
Esta función no estaba haciendo mucho ahora porque antes validaba que la reunión exista y esté abierta, pero ahora con que exista ya es suficiente. No sé si preferís que la borre o que sólo deje en la condición (!state.reunion)

2021-07-15 15:48 UTC, mpelozzi commented on frontend/src/store/reunion.js
> +        draft.reunion.abierta = true;
No entendí el comentario

2021-07-15 15:49 UTC, mpelozzi commented on frontend/src/styles/CustomTooltip.js
> +                    open={disable ? undefined : false}>
las alinee porque mientras estaba armando el tooltip me costaba leer donde estaba cada prop, puedo volverlas a una sola línea si preferis

2021-07-15 15:50 UTC, mpelozzi commented on frontend/src/tipos-vista-principal/Resumen.js
> +    'proponerPinos': DescripcionPropuestaPinos,
aaaaaah fueron cambios de linter que no vi y se pushearon igual :(

2021-07-15 15:51 UTC, ludat commented on frontend/src/api/requester.js
> +    }
Un poco ambas:

* `}else{` sin espacios (deberia haber espacio entre `}` y `else` y entre `else` y `{`)
* identacion con 4 espacio en `toast.error(...` (deberian ser 2 espacios)
* `response){` sin espacio (deberia haber espacio entre `)` y `{`
* `return Promise.reject(...` tiene 4 espacios de identacion (deberian ser 2)

2021-07-15 15:57 UTC, ludat commented on backend/src/utils/asyncMiddleware.js
> +      res.status(500).send('Request fallo');
bueno probe cosas locales, esto podria ser agregar el `next` como parametro y despues hacer `next(error)

2021-07-15 16:01 UTC, mpelozzi commented on frontend/src/tipos-vista-principal/Resumen.js
> +        <VistaDelMedioContainer style={props}>
entiendo que fue un ctrl+alt+l que hizo que todo se formatee con 4 espacios, ahí lo cambié para que sea más legible y se entienda mejor la jerarquía

2021-07-15 16:02 UTC, ludat commented on backend/src/utils/asyncMiddleware.js
> +      res.status(500).send('Request fallo');
```suggestion
const asyncMiddleware = (fn) => (req, res, next) => Promise.resolve(fn(req, res))
  .then((data) => respondWithSuccess(res, data))
  .catch((error) => {
    if (error instanceof RequestError) {
      res.status(error.statusCode).send(error.errorMessage);
    } else {
      next(error)
```

2021-07-15 17:12 UTC, mpelozzi commented on backend/src/utils/asyncMiddleware.js
> +      res.status(500).send('Request fallo');
o sea en el else sólo dejar next(error)?

2021-07-15 17:14 UTC, mpelozzi commented on frontend/src/Reunion.js
> -    </Provider>
que formato?

2021-07-15 17:26 UTC, mpelozzi commented on frontend/src/reunion/TemasHandler.js
> +            .then(() => {
duda, si el botón de cerrarReunion está bloqueado en las reuniones cerradas, debería todavía contemplar la posibilidad de que se cierre una reunión cerrada? O sea en qué momento se usaría este toast `if (!this.props.estadoReunion) {
        toast.error('La reunion ya está cerrada');`

2021-07-15 17:31 UTC, mpelozzi commented on backend/src/domain/eventos/controller.js
> +      if (!reunion.abierta && eventoRaw.type !== 'La reunion fue finalizada') {
Extraje la condición y el tipo de evento válido. Te referías a eso o querés que también ponga todos los eventos que no son validos en constantes? Si es así no se van a usar nunca acá.

2021-07-15 17:39 UTC, Lautarourtiaga commented on backend/src/domain/eventos/controller.js
> +      if (!reunion.abierta && eventoRaw.type !== 'La reunion fue finalizada') {
Quizas me falte contexto, pero me referia a poner los typos de eventos valudos en algun objeto con constantes, tipo: 

const EventTypes = {
REUNION_FINALIZADA: 'la reunion fue finalizada'
OTRO_EVENTO: 'blavla'
}

Así no hace falta chequear por string literal

2021-07-15 19:59 UTC, mpelozzi commented on backend/src/domain/eventos/controller.js
> +      if (!reunion.abierta && eventoRaw.type !== 'La reunion fue finalizada') {
hay un solo tipo de evento valido una vez que se cerró la reunión, por eso no se me ocurrió armar constantes con los demás eventos

2021-07-19 15:27 UTC, ludat approved these changes
quedaron varios lugares con linter roto pero ya estaba asi antes asi que no me parece tan catastrofico

2021-07-19 15:35 UTC, angelyan commented on backend/src/domain/eventos/eventos.test.js
> +  describe('y se quiere publicar un evento diferente de cerrar reunión', () => {
Quedó mal el texto acá

2021-07-19 15:37 UTC, angelyan commented on backend/src/domain/reuniones/reuniones.test.js
> +      expect(response.status).toEqual(400);
Estaría bueno verificar también que efectivamente no se haya modificado la reunión

2021-07-19 15:40 UTC, angelyan commented on backend/src/domain/reuniones/reuniones.test.js
> +      expect(response.status).toEqual(400);
Si la reunión está cerrada, los temas se deberían poder modificar?

2021-07-19 16:17 UTC, mpelozzi commented on backend/src/domain/reuniones/reuniones.test.js
> +      expect(response.status).toEqual(400);
no hay un endpoint para modificar los eventos, cómo se modificarían?

2021-07-19 16:41 UTC, angelyan commented on frontend/src/tipos-vista-principal/Minuta.js
> +          <CustomTooltip title='La reunion esta cerrada' disable={!reunionAbierta}>
```suggestion
          <CustomTooltip title='La reunion está cerrada' disable={!reunionAbierta}>
```

2021-07-19 16:45 UTC, angelyan commented on frontend/src/tipos-vista-principal/Minuta.js
> +          <CustomTooltip title='La reunion esta cerrada' disable={!reunionAbierta}>
Se podría extraer el title a una variable o incluso extraer un componente que sea `TooltipDeReunionCerrada` que ya tenga el title seteado.

2021-07-19 16:48 UTC, angelyan commented on frontend/src/styles/CustomTooltip.js
> +        <span>
Hace falta poner el un `span`?

2021-07-19 16:52 UTC, mpelozzi commented on frontend/src/styles/CustomTooltip.js
> +        <span>
Sí, por como funcional el tooltip de material ui si querés que funcione para un componente deshabilitado lo tenés que metera adentro de un span.

2021-07-19 16:54 UTC, angelyan commented on backend/src/domain/reuniones/reuniones.test.js
> +      expect(response.status).toEqual(400);
Este? https://github.com/10PinesLabs/ruth/blob/92762a794cf330ffe7d4e578147bf8af2708de16/backend/src/domain/temas/router.js#L12

2021-07-19 17:02 UTC, angelyan commented on frontend/src/styles/CustomTooltip.js
> +        <span>
:F:

2021-07-19 17:03 UTC, angelyan approved these changes

2021-07-20 12:46 UTC, mpelozzi commented on backend/src/domain/reuniones/reuniones.test.js
> +      expect(response.status).toEqual(400);
Nunca lo había visto :eyes: igual tampoco encuentro en qué momento se llamaría a esto, porque en el frontend no aparece. Voy a revisar a ver donde se está usando

2021-07-20 13:46 UTC, mpelozzi commented on backend/src/domain/reuniones/reuniones.test.js
> +      expect(response.status).toEqual(400);
Update, nunca se usa, probablemente quedó de una versión anterior de la aplicación. Revisé y se puede borrar.

2021-07-20 15:49 UTC, angelyan commented on backend/src/domain/reuniones/reuniones.test.js
> +      expect(response.status).toEqual(400);
Genial!

2021-07-20 18:54 UTC, mpelozzi commented on frontend/src/tipos-vista-principal/Resumen.js
> +                                   style={!reunionAbierta ? {pointerEvents: "none"} : {}}>
No sé si conviene, no todos los botones lo tienen

2021-07-21 13:24 UTC, merged