Agregar configs a reuniones preexistentes
10PinesLabs/ruth pull request #273
Opened 2021-07-20 18:45 UTC by mpelozzi

[**Link al Trello**](https://trello.com/c/gYm3kZ99)

**Aceptación**
Modifica la creación de reuniones para incluir opciones de configuración, actualmente la única opción es definir el tipo, pero está hecho con la intención de agregar un nuevo tipo a futuro con comportamiento diferente.

**Checklist**:
- [ ] Agregue tests (y los corrí localmente)
- [ ] Vi que localmente funcionara
- [ ] Probe que en la review app funcionara

2021-07-21 12:37 UTC, angelyan commented on backend/src/domain/reuniones/controller.js
> +      const reunion = { abierta: body.abierta, nombre: 'Reunion de Roots', configuracion: body.configuracion };
```suggestion
      const reunion = { abierta: body.abierta, nombre: 'Reunión de Roots', configuracion: body.configuracion };
```

2021-07-21 12:39 UTC, angelyan commented on backend/src/domain/reuniones/reuniones.test.js
> +      const response = await request(app).post('/api/reunionDeRoots').send({ abierta: true, configuracion: { tipo: 'roots' } });
Por qué se agrega el objeto `configuracion` en vez de simplemente un campo `tipo` por ejemplo?

2021-07-21 12:40 UTC, mpelozzi commented on backend/src/domain/reuniones/reuniones.test.js
> +      const response = await request(app).post('/api/reunionDeRoots').send({ abierta: true, configuracion: { tipo: 'roots' } });
Porque la idea es que a futuro se puedan configurar más cosas, y el tipo es importante porque lo próximo que voy a hacer es agregar un tipo nuevo de reunión con comportamiento diferente

2021-07-21 14:38 UTC, angelyan commented on backend/src/domain/reuniones/reuniones.test.js
> +      const response = await request(app).post('/api/reunionDeRoots').send({ abierta: true, configuracion: { tipo: 'roots' } });
Pero el `tipo` y otros campos que se quieran agregar en el futuro podrían ponerse arriba de todo:

```js
{abierta: true, tipo: 'roots', otraCosa: 'bla'}
```

En vez de

```js
{abierta: true, configuracion: { tipo: 'roots', otraCosa: 'bla'} }
```

Por qué decidieron hacerlo de la segunda forma? (No digo que esté mal, sólo me interesa saber por qué se hizo así.)

2021-07-21 14:41 UTC, angelyan commented on backend/src/domain/reuniones/controller.js
> +      const reunion = { abierta: body.abierta, nombre: 'Reunion de Roots', configuracion: body.configuracion };
Ojo que acá se está creando la reunión con lo que sea que el cliente mande como `configuracion`. Si el cliente manda
```js
{ configuracion: { tipo: 'roots', otraCosa: '2GB de texto' } }
```
Eso se va a terminar guardando todo en la base.

2021-07-21 14:46 UTC, angelyan commented on backend/src/database/migrations/20210720172629-agregarConfiguracionAUnaReunion.js
> +      type: Sequelize.JSON,
Esto con qué tipo se termina guardando en la base, como JSON o varchar/text? Hay que tener en cuenta que guardando las cosas así en vez de usar columnas para los distintos campos hace que se pierda un poco la estructura de los datos y puede ser más difícil de indexar / queryar a mano si llegara a hacer falta.

2021-07-21 14:47 UTC, ludat commented on backend/src/domain/reuniones/controller.js
> +async function generarReunion(body) {
hay tests de esta funcion?

2021-07-21 14:47 UTC, ludat commented on backend/src/domain/reuniones/reuniones.test.js
> +      reunionesRepo = new ReunionesRepo();
tiene sentido crear un nuevo repo de reuniones en vez de usar el del context de la app?

2021-07-21 14:47 UTC, ludat commented on backend/src/domain/reuniones/controller.js
> +  switch (body.configuracion.tipo) {
no estoy muy seguro de este cambio, entiendo que el tipo eventualmente va a quedar en la configuracion pero me parecia bien que estuviera top level en el json original asi podemos dar errores mas claros, podriamos mandar el tipo top level y despues nosotros agregarlo a la configuracion "a mano"

o sea, por el json que viene en el request es:

```
{nombre: 'reunion copada', tipo: 'rapida', ...}
```

y despues nosotros hacemos

```
// pseudo codigo, no tengo ganas escribir todo
reunion.configuracion = {...body.configuracion, tipo: body.tipo}
```

2021-07-21 14:47 UTC, ludat commented on backend/src/database/migrations/20210720172629-agregarConfiguracionAUnaReunion.js
> +  ),
pregunta: que pasa con las reuniones que ya estan abiertas? que tendrian en la configuracion? vamos a tener que hacer alguna migracion de datos? nos parece bien que quede en null?

2021-07-21 17:58 UTC, mpelozzi commented on backend/src/domain/reuniones/controller.js
> +  switch (body.configuracion.tipo) {
y que pasa cuando se agreguen más configs a las reuniones? vamos a tener `{nombre: 'reunion copada', tipo: 'rapida', admitePresentacion:false ...}` con n campos según los settings?

2021-07-21 18:22 UTC, mpelozzi commented on backend/src/database/migrations/20210720172629-agregarConfiguracionAUnaReunion.js
> +      type: Sequelize.JSON,
Se termina guardando como json

2021-07-21 18:34 UTC, mpelozzi commented on backend/src/domain/reuniones/reuniones.test.js
> +      const response = await request(app).post('/api/reunionDeRoots').send({ abierta: true, configuracion: { tipo: 'roots' } });
Es que en realidad el tipo es algo que en el futuro va a desaparecer, pero la idea es que eventualmente desde el front se le pueda pasar un objeto con todas las configuraciones para una reunión. El tipo está ahora porque necesitamos armar la estructura de las configuraciones. Igualmente coincido que se deberían validar esas configs para que no llegue basura. Probablemente mientras solo sea el tipo lo que se manda lo transforme en config en el backend.

2021-07-22 16:30 UTC, ludat requested changes

2021-07-22 16:30 UTC, ludat commented on backend/src/domain/reuniones/reuniones.test.js
> +      }
algunas cosas:

1. creo que jest tiene matchers para esperar que una funcion levante una excepcion y eso
2. que pasa si la funcion levanta una excepcion que no es `RequestError`? el test pasa, eso no es bueno
3. entiendo que `fail` es una funcion que tenes que llamar para que el test realmente falle, este test lo viste fallar cuando la funcionalidad no estaba implementada todavia?

2021-07-22 16:42 UTC, mpelozzi commented on backend/src/domain/reuniones/reuniones.test.js
> +      }
> este test lo viste fallar cuando la funcionalidad no estaba implementada todavia?este test lo viste fallar cuando la funcionalidad no estaba implementada todavia?

no, porque este test surgió después de que esté hecha la funcionalidad, originalmente se testeaba sólo desde el endpoint (que para mi era suficiente), y después sugeriste que agregue un test sólo para esta función

2021-07-23 02:49 UTC, ludat approved these changes

2021-07-23 13:51 UTC, angelyan approved these changes

2021-07-23 13:57 UTC, merged