Links a minuta
10PinesLabs/ruth pull request #311
Opened 2022-03-18 19:21 UTC by gperez-10pines

[**Link al Trello**](https://trello.com/c/Y1JAA18B/245-pantalla-de-minuteo-adaptar-vista-para-incorporar-el-documento-colaborativo)

**Aceptación**
Incentivar el minuteo facilitando el acceso directo a la tab.

Es parte de una historia mas grande que codearemos progresivamente.

## Lobby antes
<img width="1177" alt="Screen Shot 2022-03-18 at 16 06 49" src="https://user-images.githubusercontent.com/62029440/159070344-8853d4d2-1562-4678-ad28-da9f819dcbb4.png">

## Lobby ahora
<img width="1220" alt="Screen Shot 2022-03-18 at 16 09 43" src="https://user-images.githubusercontent.com/62029440/159070370-3d083eeb-5e53-49ee-af58-f453853ff3c3.png">

## Opinar antes
<img width="435" alt="Screen Shot 2022-03-18 at 16 11 16" src="https://user-images.githubusercontent.com/62029440/159070419-c518c482-ff59-4ece-a3be-2f16009eac39.png">

## Opinar antes
<img width="424" alt="Screen Shot 2022-03-18 at 16 12 39" src="https://user-images.githubusercontent.com/62029440/159070433-193699ad-146b-4cad-94f9-929a61f00be9.png">

2022-03-21 16:39 UTC, ludat approved these changes

2022-03-21 16:41 UTC, ludat requested changes

2022-03-21 16:41 UTC, ludat commented on frontend/src/mobile/vista.js
> +          Minuteo
Aca podria ser `Ir a la minuta` en vez de solo `Minuteo` para ir mas con el mensaje de abajo

2022-03-21 16:41 UTC, ludat commented on frontend/src/mobile/vista.js
> +
me preocupa que esta pantalla tenga tantos botones, la idea original es que era la pantalla para mobile, y que tenga tantos botones no me encanta :thinking:

2022-03-21 17:12 UTC, gperez-10pines commented on frontend/src/mobile/vista.js
> +          Minuteo
Bueno. En realidad me gustaria input de Gaby porque justamente siendo botones mobile tienen mucho texto. Podrian decir simplemente: Lobby, Presentacion, Minuta.

2022-03-21 17:12 UTC, gperez-10pines commented on frontend/src/mobile/vista.js
> +
@ludat se podria reemplazar el boton de "Ir a la presentacion" por el de la minuta. Porque una vez vas a la minuta ya podes ir a la presentacion.

El objetivo final es que haya un editor colaborativo para las minutas. Pero esa intencion va de la mano con eliminar friccion para acceder a la parte de minutas. Literal hay que hacer 3 o 4 clicks para llegar, y eso pone un freno psicologico, es mala UX.

2022-03-31 12:10 UTC, gperez-10pines commented
Lo cierro en favor de este otro: https://github.com/10PinesLabs/ruth/pull/312

De todas formas seria bienvenido el input de @giztueta

2022-03-31 21:37 UTC, closed without merging